[dirs]
zip = "zip"
git = "git"
src = "src"

[git]
repository = "https://github.com/mrogur"
packages = [
    "mvn-single",
    "mvn-multi",
    "gradle-single",
    "gradle-multi",
    "gradle-kts-multi",
    "gradle-kts"
]